[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "toffee"
version = "0.3.0"
description = "A lightweight environment-first Terraform wrapper"
authors = [
    {name = "Akhilesh Mishra", email = "akhileshmishrabiz@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.0",
    "rich>=12.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "ruff>=0.1.0",
]

[project.scripts]
toffee = "toffee.cli:app"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]